### ISSUE TITLE
[BUG] Validate pre-commit on different OS

### ISSUE THREAD

**Issue by regislon** [ltelab/disdrodb#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Black does not reformat the code while commiting changes. 

### Expected Behavior

Black should reformat the code

### Steps To Reproduce

1. Clone the repo
2. Install the venv ([instructions](https://disdrodb-dev.readthedocs.io/en/latest/install.html#install-the-python-developing-environment )) and pre-commit
3.  Create a branch "test..." This branch will not be push in the remote repo, name it whatever you want. 
4. Do a small change in one of the py file (eg. add line break before on return statement)
5. commit your changes to see if the modified file is formatted. 

### Environment

```markdown
- OS: Windows, Mac Os, Ubuntu
```

**Comment by regislon** [comment]
Hi @ghiggi, 

I've did the test on ubuntu withn a fresh installation (pip install). pre-commit works as expected. 


![Screenshot from 2022-11-30 10-30-45](https://user-images.githubusercontent.com/97044425/204762138-49a74548-01f7-4078-8fa9-b70e255d5c1f.png)


I'm wondering if the problem is not related to conda. More on that soon.

**Comment by regislon** [comment]
Hi @ghiggi I've checked with conda and pip in ubuntu and it works. Let me just see with @charlottegiseleweil if she has any issues with mac OS.

**Comment by charlottegiseleweil** [comment]
Confirm this works on MacOS 12.4

**Comment by ghiggi** [comment]
I check that on Monday. I will try to do a couple of PRs anyway.

**Comment by ghiggi** [comment]
@regislon I confirm that it works also on my Linux 20.04. 
I let you close the issue if nothing else must be tested
