### ISSUE TITLE
[BUG] Test pip install on different OS and different readers

### ISSUE THREAD

**Issue by regislon** [ltelab/disdrodb#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Test disdrodb as a external user. 

### Expected Behavior

It should work

### Steps To Reproduce

1. Pip install in a virtual env
2. Run a reader
3. See if the transformation succeed or failed

### Environment

```markdown
- OS: Ubuntu / Windows / 
- python: pip
```

### Anything else?

Sumary of thes tests and results [here ](https://docs.google.com/spreadsheets/d/10DuJhFsnJxde4EW2oUd3oiNxyqNGo4Zyn53XN4CtMb8/edit?usp=sharing).

**Comment by ghiggi** [comment]
@regislon @charlottegiseleweil 
Maybe could be worth replacing `setup.py` with `pyproject.toml` before closing this issue ;) 
More info here: 
https://pip.pypa.io/en/stable/reference/build-system/
https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/
