### ISSUE TITLE
[BUG] change import naming and function in check_configs.py

### ISSUE THREAD

**Issue by regislon** [ltelab/disdrodb#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While creating the documentation, I've noticed an error in the file `disdrodb\L0\check_configs.py`

```
``WARNING: autodoc: failed to import module 'check_configs' from module 'disdrodb.L0'; the following exception was raised:
cannot import name 'get_description_dict' from 'disdrodb.L0.standards' (C:\projects\disdrodb-fork\disdrodb\L0\standards.py)
```

Proposal : 
1. Replace Line 18 `get_description_dict,` with `get_sensor_name_dict` 
2. Replace Line 93 `description_dict = get_description_dict(sensor_name)` with `description_dict = get_sensor_name_dict(sensor_name)`

btw, I find the name of the function not totally relevant. I would rather name it  `get_sensor_variables_dict` 

What's your opinion on that @ghiggi  ? do you agree

### Environment

```markdown
*
```

**Comment by ghiggi** [comment]
I will fix that on Monday when I address https://github.com/ltelab/disdrodb/issues/118
