### ISSUE TITLE
[DOCS] Update versioning guidelines 

### ISSUE THREAD

**Issue by ghiggi** [ltelab/disdrodb#129]
The definition of breaking vs non-breaking changes should be redefined in the documentation ! 

**Current versioning doc**
DISDRODB uses Semantic Versioning. Each release is associated with a git tag of the form X.Y.Z.

Given a version number in the MAJOR.MINOR.PATCH (eg., X.Y.Z) format, here are the differences in these terms:

- MAJOR version - make breaking/incompatible API changes
- MINOR version - add functionality in a backwards compatible manner. Adding new reader
- PATCH version - make backwards compatible bug fixes

Since disdrodb is used by a broad ecosystem of both API consumers and implementers, it needs a strict definition of what changes are “non-breaking” and are therefore allowed in MINOR and PATCH releases.
In the DISDRODB spec, a breaking change is any change that requires either consumers or implementers to modify their code for it to continue to function correctly.

Examples of breaking changes include:
- Adding a feature to process a new sensor
- Adding a feature to create new DISDRODB L1 and L2 products/fields;
- Adding a feature providing new functionality to the DISDRODB API.

Examples of non-breaking changes include:
- Modifying documentation or spec language that doesn’t affect the behavior of the API directly

**Example of future versioning guidelines I would like**

Examples of breaking changes include:
- Renaming a DISDRODB product variable or metadata key 
- Changing the output format/structure of DISDRODB netCDF product 
- Adding new functionalities to the DISDRODB that affect the behavior of the software directly

Examples of non-breaking changes include:
- Fix a bug 
- Adding the configuration files to process a new sensor
- Adding a new DISDRODB L0 reader
- Adding new functionalities to the DISDRODB API that don’t affect the behavior of the API directly
- Updating the documentation 
- Internal function refactoring that doesn’t affect the behavior of the software directly

**Comment by regislon** [comment]
# done in PR #142
