### ISSUE TITLE
[BUG] pip install windows + python 3.10 + netCDF4 

### ISSUE THREAD

**Issue by regislon** [ltelab/disdrodb#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

does not work anymore with python 3.10

### Expected Behavior

should work 

### Environment

```markdown
- OS: windows
- python: 3.10
```

### Anything else?

solution : change netCDF4 version to 1.6.2

**Comment by charlottegiseleweil** [comment]
duplicate from from #111
