### ISSUE TITLE
[REFACTOR] <Refactor all paths to be understood as paths not string (to be modular cross-OS)>

### ISSUE THREAD

**Issue by charlottegiseleweil** [ltelab/disdrodb#141]
instead of 
```

PATH_FILE_WINDOWS = (
    "\\DISDRODB\\Raw\\institute_name\\campaign_name\\station_name\\file_name.tar.xz"
)
PATH_FILE_LINUX = (
    "/DISDRODB/Raw/institute_name/campaign_name/station_name/file_name.tar.xz"
)

```
do 
`PATH_FILE = os.path.join('DISDRODB','Raw','institute_name','campaign_name','station_name','file_name.tar.xz')`

**Comment by ghiggi** [comment]
I agree that it might be worth to use `Pathlib`. 
If we have time after having implemented the tests (functions and readers) and the distributed archive, I think it's a good idea to do that ;)
