### ISSUE TITLE
[FEATURE] Check config files

### ISSUE THREAD

**Issue by regislon** [ltelab/disdrodb#175]
Add new control to validate the config file.

**Comment by regislon** [comment]
Can you provide a comprehensive list of checks you would like to have, @ghiggi?

We have already discussed some of them this morning that seems to be [here ](https://github.com/ltelab/disdrodb/blob/main/disdrodb/l0/check_configs.py)

**Comment by ghiggi** [comment]
In `checks_configs` there is old code and I am not sure is still very relevant. 
For example `check_variable_keys_consistency` does not actual check and raise any error ... 

Regarding to the list of check functions to implement (@regislon): 

- [ ] `check_yaml_files_exists() `
- [ ] `check_variable_consistency()`: takes variables in `L0B_encodings.yml` and checks are present in all the other yaml 
(except the `bin_*.yaml`) 
- [ ] `check_l0b_encoding()`: check valid keys (and maybe then also values: type and possible values when relevant ... )
      - Keys: `dtype,  scale_factor, add_offset, zlib, complevel, shuffle, fletcher32, contiguous, chunksizes, _FillValue`
      - if `contiguous=False`, chunksizes specified, otherwise should be not ! 
      - if `contiguous = True`, then zlib and fletcher32 must be set to False
      - This more generally are checks for the netcdf/xarray `encoding` dictionary ! 
- [ ] `check_l0a_encoding()`: check valid types
- [ ] `check_raw_data_format()`: check valid keys (and maybe then also values: type and possible values when relevant ... )
   -  Keys: [`n_digits,  n_characters, n_decimals, n_naturals, data_range, nan_flags, dimension_order, n_values]`
   - `dimension_order, n_values` are facultative, the other are current mandatory ! 
- [ ] `check_cf_attributes()`: check that `variable_description`, `variable_long_name`, `variable_units` dict values are strings. 
- [ ] `check_bin_consistency()`
- [ ] `check_raw_array()`
  - Get keys in raw_data_format `dimension_order` and check that `chunksizes` in l0b_encoding has same length + 1 
  - Get chunksizes in chunksizes in l0b_encoding and check that if len > 1, has dimension_order key in raw_data_format

As final stuffs, you could also rename `L0A_encodings.yml` and `L0B_encodings.yml` all lower case ;) 
And in the tests, then run check_configs for all sensor names ;)

**Comment by ghiggi** [comment]
Mostly addressed by https://github.com/ltelab/disdrodb/pull/174.
@regislon I let you also add `check_configs(sensor_name)` and then close the issue.
