### ISSUE TITLE
Change ruff setting

### ISSUE THREAD

**Issue by regislon** [ltelab/disdrodb#180]
In https://github.com/ltelab/disdrodb/blob/main/pyproject.toml#L75 add `select = ["F", "E", "W", "I001"]`.
E and F are already used by default, while adding `I001` let ruff do the work of isort.
Adding `W` make ruff automatically corrects for docstring errors: https://beta.ruff.rs/docs/rules/#pydocstyle-d (just check it support the [Numpydoc ](https://numpydoc.readthedocs.io/en/latest/format.html) style, but it seems so).
You can do that in a separate PR (one for correcting the imports) and one to correct the docstring (W).
Potentially of interest to clean the code out @regislon, we could also have a look at: 
- https://beta.ruff.rs/docs/rules/#flake8-pytest-style-pt
- https://beta.ruff.rs/docs/rules/#flake8-quotes-q
- https://beta.ruff.rs/docs/rules/#flake8-return-ret
- https://beta.ruff.rs/docs/rules/#flake8-simplify-sim
- https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth
- https://beta.ruff.rs/docs/rules/#pyupgrade-up

_Originally posted by @ghiggi in https://github.com/ltelab/disdrodb/pull/179#discussion_r1180001825_

**Comment by regislon** [comment]
W has no impact on our code

**Comment by regislon** [comment]
D no effect as well

**Comment by regislon** [comment]
flake8 --docstring-convention numpy  check_metadata.py  --max-line-length=120 --select RST

![image](https://user-images.githubusercontent.com/97044425/236389667-0aaf1c2f-f20e-46b9-a2df-f7020332774b.png)

No correction applies, never ending issue

**Comment by ghiggi** [comment]
@regislon so let's add W and D just to have it ! And let specify "I001" to sort the packages ;)
