### ISSUE TITLE
is there an option to create single netcdf files instead of a concatenated one?

### ISSUE THREAD

**Issue by saveriogzz** [ltelab/disdrodb#3]
Hey guys, I am running the library over some files and I was wondering if there is any option to singularly create netcdf files, instead of one with all the data present in all the raw data files.
Thanks!

**Comment by ghiggi** [comment]
The current parser converts all raw data files to the Apache Parquet Dataframe and then into a single NetCDF. 
But it would be enough to loop over each raw data file instead of (additionally to) each station to generate a netCDF for each raw data file ;)

**Comment by saveriogzz** [comment]
Hey guys, I followed @ghiggi suggestions of creating an inner for loop that looks for single files. I found out that the function `read_L0_raw_file_list` that was called in the parser, looks for all the files present in the directory by default, so in https://github.com/DISDRONET/disdrodb/commit/a7a3dd3077a375df3a9653b570811cadd03cc066 I added the function `read_L0_raw_file` that basically does the same, but for a single file. It is now correctly creating L0 parquet files.

Regarding L1 (netcdf) files, the conversion has worked until I had the old file named `CABAUW_sPAR001.parquet` in the directory. I guess this is because the function `read_L0_data`, called when processing to L1, is also looking at the directory as a whole and not searching for a single file as I am now receiving the error
```python
ile "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/readers/DELFT/parser_RASPBERRY.py", line 494, in <module>
    main()
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/readers/DELFT/parser_RASPBERRY.py", line 449, in main
    df = read_L0_data(processed_dir, station_id, lazy=lazy, verbose=verbose, debugging_mode=debugging_mode)
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/io.py", line 390, in read_L0_data
    check_L0_is_available(processed_dir, station_id)
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/io.py", line 376, in check_L0_is_available
    raise ValueError(msg)
ValueError: Need to run L0 processing first. The Apache Parquet file /tmp/Processed/CABAUW/L0/CABAUW_sPAR001.parquet is not available.
```

My suggestions would be to keep the functions as "atomic" as possible (e.g. look for files instead of whole directories). What do you guys think?

**Comment by ghiggi** [comment]
Before closing this, @saveriogzz provide the parser you developed in the template folder ;)
