### ISSUE TITLE
[FEATURE] function list_readers()

### ISSUE THREAD

**Issue by charlottegiseleweil** [ltelab/disdrodb#36]
**Solution**
Function to list automatically all available readers .

**Comment by ghiggi** [comment]
In association to this, we could think of a function searching for the DISDRODB stations available (or meeting certain criteria) once a DISDRODB directory is specified. This is partially related to #74 

We could also think to have some sort of dynamic `disdrodb.config` where is possible to set the base_directory just after the imports on the top of the data exploratory scripts
