### ISSUE TITLE
[BUG] <replace import statement in run_DELFT_processing>

### ISSUE THREAD

**Issue by mschleiss** [ltelab/disdrodb#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The import statements for the parser module need to be updated 

Current line (points to wrong folder)

from disdrodb.utils.parser import get_parser_cmd 

replace with 

from disdrodb.pipeline.utils_cmd import get_parser_cmd

### Environment

```markdown
- OS:
- python:
```

**Comment by regislon** [comment]
only one file. Holland is the only reader
