### ISSUE TITLE
[BUG] <NETCDF: nc_def_var_deflate fails with string variables: Filter error: bad id or parameters or duplicate filter>

### ISSUE THREAD

**Issue by mschleiss** [ltelab/disdrodb#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a netcdf file from an xarray object in L0B_processing.py, the code crashes as soon as you try to add compression on string variables.  

### Expected Behavior

Set the compression level to 0 for weather_code_metar_4678 and weather_code_nws in L0B_encoding.yml

### Environment

```markdown
- OS:
- python:
```

**Comment by ghiggi** [comment]
@mschleiss this bug has been solved by the PR https://github.com/ltelab/disdrodb/pull/68
