### ISSUE TITLE
[REFACTOR] Remove templates folder

### ISSUE THREAD

**Issue by charlottegiseleweil** [ltelab/disdrodb#56]
@ghiggi Okay we're ready for the big leap - now with the notebook as a line-by-line replacement of reader_template.py; people can jsut copy that with their own data to avoid confusion. There should be no reason to keep this "templates" folder !

Let's be consistent with collaborative open-source good practices, if you want to see what people are doing, you can always go in their forks, but they shouldn't have to commit half-baked WIP readers development into the main repo .

I'm going ahead and making the bold move - so we can then rename every "parser" as "reader" to avoid confusion (see #46)

**Comment by ghiggi** [comment]
Fine with that. 
In addition to the notebook, I would still provide a notebook equivalent `reader_template.py` file to execute line-by-line for people that are not used to Jupyter Notebooks and they prefer for example to code in Spyder, RStudio or similar GUIs.

**Comment by charlottegiseleweil** [comment]
Debatable .. I would not recommend to keep two versions, (notebook + py script), I think the risk to have the two versions not up-do-date is too high. Nowadays most people use notebooks, and if they don't, they can read the notebook contents in the doc and paste the cells in order to run line-by-line style .. no ?

Just my recommendation - not strong feelings if you feel more strongly we can keep both (maybe ask opinions form colleagues in yr lab, what format they would use?)
