### ISSUE TITLE
[BUG] Error due to processed folder deletion and recreation 

### ISSUE THREAD

**Issue by regislon** [ltelab/disdrodb#60]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

While working with jupiter notebook, the log created under data\DISDRODB\Processed\NETHERLANDS\DELFT` blocks  the deletion and recreation of the process folder 

### Expected Behavior

In `raw_dir, processed_dir = check_directories(raw_dir, processed_dir, force=False)`  If force = False --> no erreor should be raised if the folder exists already 

### Steps To Reproduce

just run twice the cell under **2. Initialization**

**Comment by ghiggi** [comment]
@regislon I think is behaving correctly. If you set `force=False`, you don't want to risk overwriting existing data. So it raises an error. If you set `force=True`, you enable to (over)write also if the folder already exists.

Additional thought: when we choose to convert every single file in the corresponding netCDF, check the code works correctly also by setting `force=False`.

**Comment by regislon** [comment]
ok then we should add in the notebook "Do not run this cell twice". 

This behaviour is due to the fact that the notebook creates an log file in the proceessed folder that is editing mode as long as the jupiter notebook sever is running.
