### ISSUE TITLE
[FEATURE] Creation of disdrodb_archive repository for sample data and metadata 

### ISSUE THREAD

**Issue by ghiggi** [ltelab/disdrodb#73]
This issue aim to expose the idea of creating a separate repository called `disdrodb_archive` where to locate sample data and metadata for each station and reader.

The main goals are to:
- share with the community the DISDRODB stations metadata in order to collaboratively edit it;
- share with the community the DISDRODB stations issue files in order to collaboratively improve the quality of the dataset;
- facilitate the testing of the L0 readers. 

Related to this point, in the DISDRODB full archive, we could better enforce the format and structure of the raw files within each station directory, by for example banning heterogenous archive/compression formats (tar, gzip, bz2,...) or directory nested structures. 
For portability of the DISDRODB raw archive, it might be useful to have all files within a station zipped in a single directory ... especially for stations where the deployment has terminated and we do not expect further data stream. 

This feature request will require the development of code to synchronize between this repo metadata and the DISDRODB Full Archive.

In the context of this PR ... please deprecate the use of `station_id` in favor of `station_name`. 
The station directory must have the same (hopefully explanatory) name as the corresponding `station_name` key in the metadata

**Comment by ghiggi** [comment]
Yes !!! @regislon 
Little comments:
 - download not downalod if you want to put  the picture on the doc
 - we will also place the issue directory and issue.yml on disdrodb-data
 - info content to be defined 
 - docs repository maybe could be optional ... but depend on available space

**Comment by regislon** [comment]
ok great, I aggree to all of you points.  I don't need a meeting this morging with you. I can starting on it...

I'll keep you updated @ghiggi

**Comment by ghiggi** [comment]
Ok
