### ISSUE TITLE
[Refactor] : Simplify code

### ISSUE THREAD

**Issue by regislon** [ltelab/disdrodb#97]
It could be simplified with the follow code : 
```
start_time = pd.to_datetime(ds["time"].values[0])
end_time =  pd.to_datetime(ds["time"].values[-1])
start_time_str = start_time.strftime(format)
end_time_str = end_time.strftime(format)
```

I wonder if it's not more useful to return the `pd.Timestamp` / `datetime.datetime` start_time and end_time 
and then convert to string with `strftime` when defining the filepaths. 

The function could be called `get_start_end_time(ds)`

_Originally posted by @ghiggi in https://github.com/ltelab/disdrodb/pull/92#discussion_r991925660_

**Comment by ghiggi** [comment]
Fixed by https://github.com/ltelab/disdrodb/pull/105
