### ISSUE TITLE
[refactor]  `data_source` instead of institute/country

### ISSUE THREAD

**Issue by regislon** [ltelab/disdrodb#99]
We decided to use `data_source` instead of institute/country right?  
Please adapt the code and docs for that ;) 
Example: `get_data_source`

_Originally posted by @ghiggi in https://github.com/ltelab/disdrodb/pull/92#discussion_r991913705_

**Comment by ghiggi** [comment]
Fixed by https://github.com/ltelab/disdrodb/pull/105
